CREATE ROLE "taskMgmtUser" NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'tmu123';
GRANT DELETE, SELECT, INSERT, UPDATE ON TABLE taskmgmt.public.task TO "taskMgmtUser";
GRANT DELETE, SELECT, INSERT, UPDATE ON TABLE taskmgmt.public.task_status TO "taskMgmtUser";
GRANT DELETE, SELECT, INSERT, UPDATE ON TABLE taskmgmt.public."user" TO "taskMgmtUser";